### ISSUE TITLE
Failed import

### ISSUE THREAD

**Issue by EddieEldridge** [jbhaywood/5e-statblock-importer#22]
**Statblock**
```
BOGBUG
Small beast, chaotic evil

STR 
5 (–3)

DEX 
17 (+3)

CON 
12 (+1)

INT 
6 (–2)

WIS 
13 (+1)

CHA 
10 (+0)

Armor Class 17 (natural armour)
Hit Points 22 (5d6 + 5)
Speed 20 ft.
Senses passive Perception 11, darkvision 60 ft.
Languages —
Challenge 2 (450 XP)
Burrow. The bogbug can take a bonus action to hide by digging 
itself into mud or debris. It is effectively invisible while hidden.
Actions
Bite. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 
1 piercing damage.
Command. The bogbug performs music focused on a single 
target. A creature of the bogbug’s choice within 30 feet of it must 

make a DC 13 Charisma saving throw. On a failure, the creature 
has a choice: follow the bogbug’s command (which is either to 
Dash into an area of difficult terrain or to Lie Down and become 
prone), or gain a level of Exhaustion.
Exclude. The bogbug’s wings whisper an eerie tune and each 
creature within 30 feet of it other than itself must make a DC 
13 Charisma saving throw. On a failure, the creature becomes 
frightened of the area. A creature that starts its turn outside the 
area is no longer frightened. A character that succeeds at the 
saving throw is immune for 24 hours.
Frustrate. The bogbug plays a song meant to rile up all who listen 
to it. Each creature within 30 feet of the bogbug other than itself 
must make a DC 13 Charisma saving throw. On a failure, the 
creature has a choice: move toward another creature that it can see 
and make a melee attack against that creature if it is in reach, or 
gain a level of exhaustion.
```
**Error**
```
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'passive')
[Detected 4 packages: skill-customization-5e, lib-wrapper, system:dnd5e, 5e-statblock-importer]
    at Actor5e.patchedPrepareData (skl-customization.js:27:73)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at Actor5e.🎁CONFIG.Actor.documentClass.prototype.prepareData#0 (libWrapper-wrapper.js:189:20)
    at Actor5e._initialize (foundry.js:10558:12)
    at new Document (document.mjs:52:10)
    at new BaseActor (documents.mjs:62:1)
    at new <anonymous> (foundry.js:10531:5)
    at new Actor (foundry.js:13388:5)
    at new Actor5e (entity.js:14:16)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:9980:15)
    at ClientDatabaseBackend._createDocuments (foundry.js:9920:33)
    at ClientDatabaseBackend.create (backend.mjs:96:22)
    at async Function.createDocuments (document.mjs:338:21)
    at async Function.create (document.mjs:439:21)
    at async Function.parseInput (sbiParser.js:95:27)
    at async HTMLButtonElement.<anonymous> (sbiWindow.js:58:21)
onError @ foundry.js:319
```

**Comment by EddieEldridge** [comment]
I am using this version of Skill-Customization-5e (https://github.com/NoxDied/FVTT-Skill-Customization-5e)

**Comment by jbhaywood** [comment]
I opened a [pull request](https://github.com/NoxDied/FVTT-Skill-Customization-5e/pull/3) to fix this issue, so I'm going to go ahead and close it on this end.
